### ISSUE TITLE
example build fail.

### ISSUE THREAD

**Issue by rdtor** [aklevy/ofxOSSIA#13]
of-workspace/addons/ofxOssia/src/Parameter.h:180:19: error: cannot convert ‘opp::node’ to ‘opp::node*’ in return
     return _impl->_currentNode;
                   ^~~~~~~~~~~~
make[1]: *** [/home/s***/of-workspace/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:217: obj/linux64/Release/src/InteractiveCircle.o] Error 1
make[1]: Leaving directory '/home/s***/of-workspace/addons/ofxOssia/example-simple'
make: *** [/home/s***/of-workspace/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

**Comment by bltzr** [comment]
Hi! 

actually ofxOssia is not maintained anymore, you should use [ofxOscQuery](https://github.com/bltzr/ofxOscQuery) instead
