### ISSUE TITLE
published name is not local_name

### ISSUE THREAD

**Issue by pach** [aklevy/ofxOSSIA#8]

**Comment by bltzr** [comment]
I have pulled and rebuilt and the device still shows up as "ossia" in i-score
![viuzrtiv](https://user-images.githubusercontent.com/113982/27920599-6b0a597a-6275-11e7-9383-3b87722ea282.png)
did I miss something ?

**Comment by bltzr** [comment]
this doesn't seem to be working on my side (even after building a few times and re-cloning the repo from scratch), so I'm reopening the issue... maybe you forgot to commit/push something, @pach ?
